# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbaa1ca83dc7eaafa17e42d7bf75a4235544d15912d4e9205a040f4c062599a372bb1b0f26f1a3286c67809e57fa9a0d645c4468e5919958c5e8b2d0b897f922

test:
  secret_key_base: daed5ed56d75567d55ede42eafa3bc029658ffc8354f667c61f3457196737fb6a9fbae01dca9bcb01212e0cf102bd371e864cbcc7f9937d4d67f35e1698090e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: UA-36788567-4
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>